grafana:
  image: grafana/grafana:latest
  ports:
    - '3000:3000'
  volumes:
    - ./:/var/lib/grafana/plugins/ngilive-map
    # - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
