version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - ./:/var/lib/grafana/plugins/ngilive-map
      - grafana-storage:/var/lib/grafana
      # - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
volumes:
  grafana-storage:
